-- Import operators/sellers data from text file
-- Format: "Operator/Seller — Application"

INSERT INTO operator_reference (operator_name, application_name, is_p2p, is_active) VALUES
('NBU 2P2 U PLAT UZCARD, 99', 'Milliy 2.0', true, true),
('NBU P2P HUMO UZCARD>', 'Milliy 2.0', true, true),
('NBU P2P HUMOHUMO>tas', 'Milliy 2.0', true, true),
('NBU P2P UZCARD HUMO, 99', 'Milliy 2.0', true, true),
('PSP P2P AKSIYA>TASHK', 'MyUztelecom', true, true),
('PSP P2P AKSIYA, UZ', 'MyUztelecom', true, true),
('PSP P2P HUMO2UZCARD>', 'MyUztelecom', true, true),
('UPAY P2P', 'Humans', true, true),
('UPAY P2P, UZ', 'Humans', true, true),
('UPAY Humo2Uzcard>TOS', 'Humans', true, true),
('UPAY UZCARD2HUMO, UZ', 'Humans', true, true),
('UPAY HUMO2HUMO P2P>T', 'Humans', true, true),
('DAVR UPAY HUMANS UZCARD2UZCARD, UZ', 'Humans', true, true),
('DAVR UPAY HUMANS UZCARD2HU, UZ', 'Humans', true, true),
('TENGE UNIVERSAL P2P, UZ', 'Tenge24', true, true),
('T24 P2P Humo to Uzca', 'Tenge24', true, true),
('NEW DBO UZKART-HUMO, UZ', 'Tenge24', true, true),
('TENGE 24 P2P UZCARD UZCARD, UZ', 'Tenge24', true, true),
('TENGE 24 P2P UZCARD HUMO, UZ', 'Tenge24', true, true),
('Tenge24 P2P UZCARDHU', 'Tenge24', true, true),
('TENGE-24 WS P2P INTERBANK, UZ', 'Tenge24', true, true),
('TENGE-24 WS P2P INTERBANK SPISANIYE UZCA, UZ', 'Tenge24', true, true),
('TENGE-24 WS P2P U2H-E, UZ', 'Tenge24', true, true),
('TENGE24 WS P2P H2UEW', 'Tenge24', true, true),
('XAZNA OTHERS 2 ANY, 99', 'Xazna', true, true),
('XAZNA OTHERS TO HUMO, 99', 'Xazna', true, true),
('XAZNA HUMO 2 UZCARD', 'Xazna', true, true),
('XAZNA P2P>TOSHKENT', 'Xazna', true, true),
('DAVR MOBILE UZCARD UZCARD, UZ', 'Davr Mobile', true, true),
('DAVR MOBILE P2P H2U>', 'Davr Mobile', true, true),
('DAVR MOBILE P2P H2H>', 'Davr Mobile', true, true),
('DAVR MOBILE HUMO UZCARD, UZ', 'Davr Mobile', true, true),
('DAVR MOBILE P2P KOMIS, UZ', 'Davr Mobile', true, true),
('DAVR MOBILE UZCARD HUMO, UZ', 'Davr Mobile', true, true),
('HAMKORBANK ATB, UZ', 'Hamkor', true, true),
('HAMKOR P2P UZKARD>AN', 'Hamkor', true, true),
('OQ P2P, UZ', 'OQ', true, true),
('OQ P2P>TASHKENT', 'OQ', true, true),
('TOSHKENT SH., AT KHALK BANKI BOSH AMALIY, 99', 'Paynet', true, true),
('UZPAYNET>Shayxontoxu', 'Paynet', true, true),
('PAYNET HUM2UZC NEW>T', 'Paynet', true, true),
('UZPAYNET>Toshkent Sh', 'Paynet', true, true),
('UZCARD OTHERS 2 ANY PAYNET, 99', 'Paynet', true, true),
('PAYNET P2P HUM2UZC>S', 'Paynet', true, true),
('TOSHKENT SH., MIKROKREDITBANK ATB BOSH, UZ', 'Mavrid', true, true),
('MKBANK MAVRID UZCARD', 'Mavrid', true, true),
('MKBANK P2P UZCARD MAVRID, UZ', 'Mavrid', true, true),
('UZCARD PLYUS P2P, 99', 'Joyda', true, true),
('UZCARD PLYUS P2P HUMO BOSHQA BANK, 99', 'Joyda', true, true),
('UZCARD P2P, UZ', 'Agrobank', true, true),
('ASAKABANK HUMO UZCAR', 'Asakabank', true, true),
('TOSHKENT SH., ASAKA AT BANKINING BOSH, 99', 'Asakabank', true, true),
('ASAKABANK UZCARD HUMO P2P BB, 99', 'Asakabank', true, true),
('ASAKA HUMO UZCARD P2', 'Asakabank', true, true),
('SMARTBANK P2P O2O UZCARD, UZ', 'SmartBank', true, true),
('SMARTBANK UZCARD HUMO P2P, UZ', 'SmartBank', true, true),
('SmartBank P2P UZCARD', 'SmartBank', true, true),
('SmartBank P2P HUMO U', 'SmartBank', true, true),
('SmartBank P2P O2O HU', 'SmartBank', true, true),
('BEEPUL UZCARD 2 UZCARD, UZ', 'Beepul', true, true),
('BEEPUL UZCARD 2 HUMO, UZ', 'Beepul', true, true),
('PAYWAY 05, UZ', 'PayWay', true, true),
('PAYME P2P, UZ', 'Payme', true, true),
('UB PEREVOD CROSSBORDER 6 SEND, UZ', 'UzumBank', true, true),
('SQB MOBILE UZCARD P2P UZCARD, UZ', 'SQB', true, true),
('SQB MOBILE HUMO P2P', 'SQB', true, true),
('CHAKANAPAY UZCARD TOUZCARD, UZ', 'Chakanapay', true, true),
('ChakanaPay Humo to Uzcard', 'Chakanapay', true, true),
('ChakanaPay Humo Uzcard', 'Chakanapay', true, true)
ON CONFLICT (operator_name, application_name) DO NOTHING;

-- Show statistics
SELECT
    COUNT(*) as total_records,
    COUNT(DISTINCT application_name) as unique_applications,
    COUNT(CASE WHEN is_p2p THEN 1 END) as p2p_count
FROM operator_reference;

-- Show sample data
SELECT id, operator_name, application_name FROM operator_reference LIMIT 5;
